[manager]
vm-wazuh-manager ansible_host=20.255.112.239 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/key-wazuh-manager.pem

[agents]
vm-agent-01 ansible_host=104.208.124.163 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/key-wazuh-agent01.pem
vm-agent-02 ansible_host=20.2.49.57      ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/key-wazuh-agent02.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
